### ISSUE TITLE
有一个消费者组的问题

### ISSUE THREAD

**Issue by honkkki** [lixd/kafka-go-example#4]
https://github.com/lixd/kafka-go-example/blob/bd7617a1898fc954710a3753281fcc1f3f54211b/consumer/group/group_consumer.go#L76-L83

这个cg.Consume(ctx, []string{topic}, handler)好像是block的 后面的逻辑能走到么
```go
			// 如果 context 被 cancel 了，那么退出
			if ctx.Err() != nil {
				return
			}
```

**Comment by lixd** [comment]
@honkkki  
正常情况走不到，会阻塞在这里，不过KafkaServer端触发Rebalance,导致订阅关系变化时时会返回的，具体见[Kafka(Go)教程(十一)---Consumer Group & Rebalance](https://www.lixueduan.com/post/kafka/11-consumer-group-rebalance)

相关源码如下：
[Consume](https://github.com/Shopify/sarama/blob/main/consumer_group.go#L170-L209):
```go
func (c *consumerGroup) Consume(ctx context.Context, topics []string, handler ConsumerGroupHandler) error {
	go c.loopCheckPartitionNumbers(topics, sess)

	// 正常会阻塞在这里，直到 ctx 被取消
	// sess.ctx 其实是我们传进来的 ctx 下的子 ctx，除了外部取消之外，
	// sarama 内部也有地方调用取消，具体见下面的`loopCheckPartitionNumbers`这个方法
	<-sess.ctx.Done()

	// Gracefully release session claims
	return sess.release(true)
}

```

[loopCheckPartitionNumbers](https://github.com/Shopify/sarama/blob/main/consumer_group.go#L528-L559) 就是一直检测 Kafka Server 端是否触发了Rebalance，导致分配给每个消费者的partition发生变化，如果有则取消sess.ctx,让Consume方法退出。
```go
func (c *consumerGroup) loopCheckPartitionNumbers(topics []string, session *consumerGroupSession) {
	pause := time.NewTicker(c.config.Metadata.RefreshFrequency)
	defer session.cancel()
	defer pause.Stop()
	var oldTopicToPartitionNum map[string]int
	var err error
	if oldTopicToPartitionNum, err = c.topicToPartitionNumbers(topics); err != nil {
		return
	}
	for {
	// 每过一段时间会检测topic对应的分区是否一致
		if newTopicToPartitionNum, err := c.topicToPartitionNumbers(topics); err != nil {
			return
		} else {
			// 如果不一致就返回了
			// kafka server端触发Rebalance时就会出现分区不一致的情况
			// 然后外部的 Consume 方法就会返回
			// 因此需要在一个循环中调用 Consume 方法
			// 便于在退出后再次调用 Consume 方法,从新的 partition 中消费
			for topic, num := range oldTopicToPartitionNum {
				if newTopicToPartitionNum[topic] != num {
					return // trigger the end of the session on exit
				}
			}
		}
		select {
		case <-pause.C:
		case <-session.ctx.Done():
			Logger.Printf("loop check partition number coroutine will exit, topics %s", topics)
			// if session closed by other, should be exited
			return
		case <-c.closed:
			return
		}
	}
}
```

**Comment by honkkki** [comment]
> 

感谢解答

**Comment by rayoluo** [comment]
```go
func newConsumerGroupSession(ctx context.Context, parent *consumerGroup, claims map[string][]int32, memberID string, generationID int32, handler ConsumerGroupHandler) (*consumerGroupSession, error) {
	// init offset manager
	offsets, err := newOffsetManagerFromClient(parent.groupID, memberID, generationID, parent.client)
	if err != nil {
		return nil, err
	}

	// init context
	ctx, cancel := context.WithCancel(ctx)

	// init session
	sess := &consumerGroupSession{
		parent:       parent,
		memberID:     memberID,
		generationID: generationID,
		handler:      handler,
		offsets:      offsets,
		claims:       claims,
		ctx:          ctx,
		cancel:       cancel,
		hbDying:      make(chan none),
		hbDead:       make(chan none),
	}

```
这里包了一层，子context取消不会影响外层的ctx吧

**Comment by kiripeng214** [comment]
> ```go
> func newConsumerGroupSession(ctx context.Context, parent *consumerGroup, claims map[string][]int32, memberID string, generationID int32, handler ConsumerGroupHandler) (*consumerGroupSession, error) {
> 	// init offset manager
> 	offsets, err := newOffsetManagerFromClient(parent.groupID, memberID, generationID, parent.client)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	// init context
> 	ctx, cancel := context.WithCancel(ctx)
> 
> 	// init session
> 	sess := &consumerGroupSession{
> 		parent:       parent,
> 		memberID:     memberID,
> 		generationID: generationID,
> 		handler:      handler,
> 		offsets:      offsets,
> 		claims:       claims,
> 		ctx:          ctx,
> 		cancel:       cancel,
> 		hbDying:      make(chan none),
> 		hbDead:       make(chan none),
> 	}
> ```
> 
> 这里包了一层，子context取消不会影响外层的ctx吧

context 的 cancel 只会影响节点下的子context，不会影响到父的context
