### ISSUE TITLE
ConsumeClaim的写法可能造成 read tcp xxx: i/o timeout

### ISSUE THREAD

**Issue by fangxlmr** [lixd/kafka-go-example#6]
https://github.com/lixd/kafka-go-example/blob/47ee77d71cc9c7d6a952b268f7ade66ef685f879/consumer/group/group_consumer.go#L41

我在生产环境遇到了这个问题 https://github.com/Shopify/sarama/issues/1192 ，有个修复是这样的 
 https://github.com/Shopify/sarama/pull/2240
试一下增加一个select session.Context是不是能解决

**Comment by lixd** [comment]
thanks, already update~
